# General Settings
format = "$nix_shell$directory $git_branch $git_status $cmd_duration\n$character"
add_newline = true

# Prompt Symbols
[character]
success_symbol = "[>](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[Vi](bold yellow)"

# Username module
[username]
style_user = "blue"
style_root = "bold red"
show_always = true
format = "[$user]($style)"

# Hostname module (only show for SSH, no 'in')
[hostname]
ssh_only = true
style = "bold magenta"
format = "@[$hostname]($style)"

# Directory
[directory]
truncation_length = 5
truncate_to_repo = false
style = "cyan"
format = "[$path]($style)"

# Git branch
[git_branch]
symbol = ""
style = "bold purple"
only_attached = true
format = "[$symbol$branch]($style)"

# Git status
[git_status]
style = "bold red"
format = "[$all_status]($style)"

# Command duration
[cmd_duration]
min_time = 10000  # ms
style = "bold italic yellow"
format = "[$duration]($style)"

# Git metrics off
[git_metrics]
disabled = true

[nix_shell]
format = "[$symbol]($style)"
symbol = " "
style = "bold cyan"
pure_msg = "pure"
impure_msg = "impure"
unknown_msg = ""
